.github/workflows/push.yml, package.json
Now that builds are working again...
- Automate notifications to Github Pages API that a new release has occurred.
- Cache dependencies to speed up overall build time
- Artefact the generated website
- Fragment workflow into separate build, test and deploy steps
=> Workflow improvements

gatsby-node.js, package.json, src/lib/slug-generation.js, tests/lib/slug-generation.test.js
Refactor out slug generation so that it may be tested.  This enables a safe refactor for #202's breaking change.
=> Test slug generation

.github/workflows/monorepo-deploy.yml
In the deploy task, explicitly state that we depend on the prepare task.
The prepare task provides the matrix context, and without it, the deploy matrix fails!
=> Explicitly depend on prepare for deploy

packages/personal-website/gatsby-config.js
Create FileNodes for picture directory, and use the copy-files-plugin to copy the entire directory.
Without a FileNode this should have never worked - meanwhile the copy-files-plugin always resolved to the first FileNode within the directory, not the directory itself.
This meant that the pictures folder was not copied.
=> Create FileNodes for pictures

packages/personal-website/static/redirects.json, packages/worker-cdn-prod/index.js
Read the /redirects.json file on origin.
To allow an origin incapable of serving a redirect (i.e. S3, Github Pages) to let Cloudflare know if something has moved/changed.
=> Add support for redirects generated by origin

.github/workflows/build-test-deploy.yml, .github/workflows/monorepo-deploy.yml
Following the work in #744 & #1143, split Gatsby from monorepo CI
Gatsby tends to have the longest build times, and including its dependencies *really* slows down the monorepo CI pipeline.
=> Exclude @alexwilson/personal-website from Monorepo CI

packages/personal-website/gatsby-node.js, packages/personal-website/src/components/webmentions.js, packages/personal-website/src/templates/article.js, packages/personal-website/static/redirects.json
Migrate away from permalink-style URLs to UUID format.
Mostly a long-term pet-peeve, the permalinks have been a *real* pain to maintain and are absolutely an artefact of working with a static site. This enables sourcing pages dynamically from a CMS which is in-line with Edge.
=> Migrate slugs to UUIDs

.github/workflows/build-test-deploy.yml
Force Gatsby to use local packages, and bring local dependencies in-scope.
Ever since scoping the lerna calls, Gatsby hasn't had access to the correct version of the `@alexwilson/content` package which resulted in failing builds.  This brings that package back in scope, and also requires that local packages are always used in preference to externally published ones.
=> Force Gatsby to use local packages

.github/workflows/build-test-deploy.yml, .github/workflows/monorepo-deploy.yml
Simplify `on:` directive in Github Action configuration so that `pull_request` events can kick off builds.
Bots such as Dependabot don't fire a test run meaning that it's hard to merge PRs with any real confidence.  Also this has been rather awkward to read.
=> Run Actions on PR events

.github/workflows/auto-approve.yml
Github recently released a security update which sandboxes actions preventing them from having read-access to secrets in `pull_request` events.  The post in question is here: https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
Both of these actions are "safe" in that they do not run unknown 3rd party code.
Move from `pull_request` (which is sandboxed) to `pull_request_target`.
=> chore: Move dependencies to `pull_request_target`

.github/workflows/auto-approve.yml
Following on from #1518 - GitHub have updated how permissions in GitHub actions work.  Unfortunately this means that Dependabot workflows no longer have access to any read/write secrets.
Update to run in the `pull_request_target` scope, for when a label has been added (or removed).
This PR also updates the condition to check the pull_request payload for its original creator instead of relying on the individual actor - so that it is easier to debug!
=> feat: Auto-update dependencies when labelled

.github/workflows/build-test-deploy.yml
To enable publishing when changes are made to other systems (and via API).
Subscribe to the `content-update` `repository_dispatch` event.
=> feat: Add GitHub content-update repository dispatch

.github/workflows/monorepo-deploy.yml
Following https://github.com/cloudflare/wrangler/pull/1780 this should no longer be needed.  see #1533.
=> chore: Remove wrangler install

.github/workflows/monorepo-deploy.yml
In an effort to improve CI performance & improve the visibility of scheduled builds...
Test & deploy only the packages which have been updated since the last build.
=> feat(ci): Only run pipeline for updated packages

.github/workflows/build-test-deploy.yml, .github/workflows/monorepo-deploy.yml
=> Update default branch name to `main`

packages/cms/client/config.yml
For whatever reason I'm still frequently hit by GitHub rate limits (there's probably something accessing my account, as me, a lot...) which results in sign-outs in Netlify CMS.
Enable experimental graphQL-mode for Netlify CMS
=> feat: Use graphQL for Netlify CMs

packages/gatsby-remark-rewrite-images/rewrite-images.js
I accidentally broke images by removing the trailing slash which allows the pictures path to be replaced.
Replace `https://alexwilson.tech/` with `/`
This library probably needs some tests!
=> Remove full-domain only

packages/cms/client/config.yml
Trying to make it easier to identify the status of an item in the editorial workflow of Netlify CMS.
Change the status prefix from the default of `netlify-cms/` to `status/`!
=> chore(cms): Change label prefix to status

.github/workflows/build-test-deploy.yml
To improve maintainability I'm trying to remove some of the more esoteric parts of the deployment pipeline.
Migrate `pages update` to `octokit/request-action@v2.x`.
=> chore(gh-pages): Migrate to octokit

packages/cms/lib/uuid-v4.js, packages/cms/package.json
`netlify-cms` depends on an rather old version of `uuid` which in results in a module resolution collision whenever attempting to use a newer version of `uuid` (i.e. for ESM builds)
Alias the now-discontinued `uuid/v4` to a module which exports `v4` UUID generation, until Netlify update this dependency.
See: https://github.com/netlify/netlify-cms/pull/4270
=> CMS: Temporarily alias uuid/v4 to an ES module

packages/cms/package.json
ParcelJS 2.0 introduces scope-hoisting as a default option.  When it is enabled , the `cms` project builds successfully HOWEVER those builds then all fail with `parcelRequire is not defined`
Disable scope-hoisting.
See: 
- https://github.com/parcel-bundler/parcel/issues/1996 
- https://github.com/parcel-bundler/parcel/issues/5973
- https://github.com/parcel-bundler/parcel/issues/5814
=> fix(cms): Disable parcel scope-hoisting as it does not work!

.github/dependabot.yml, .github/workflows/build-test-deploy.yml, .github/workflows/monorepo-deploy.yml, packages/gatsby-remark-rewrite-images/package-lock.json, packages/gatsby-remark-rewrite-images/package.json
As of v3, all unist packages are now ES modules.  ES modules don't play nicely with Gatsby 2.x.
Until Gatsby is upgraded to 3.x, downgrade & ignore updates to v3 `unist-util-visit` in `@alexwilson/gatsby-remark-rewrite-images`
=> chore: Ignore unist-util-visit updates

packages/cms/package-lock.json, packages/cms/package.json
Dependabot has updated several parcel packages to their latest nightlies - including the configuration base.  This has broken CMS builds for the past month.
Update parcel to the latest beta.
=> chore: Bump parceljs

.github/workflows/build-test-deploy.yml
Previously GitHub Pages deployments couldn't be triggered by a GitHub action, and so a manual API call to the gh-pages API was required.  For the past few weeks that no longer seems to be the case, and I've noticed that regularly there's 2x gh-page deployments happening.
Remove the gh-page deployment creation API call from the `build-test-deploy` workflow.
Yeah - monitor for this for a bit JUST TO BE SURE?
=> chore(ci): Remove gh-pages rebuild request

.github/actions/github-pages/entrypoint.sh
Today pushes to GitHub Pages fail as the GitHub workspace is owned by another user to the one running git, as seen in: https://github.com/alexwilson/frontend/runs/6138055046?check_suite_focus=true
Add the current workspace to the safe directory allowlist.
=> fix(github-pages): Add workspace as safe directory

.github/actions/github-pages/entrypoint.sh
Following https://github.com/alexwilson/frontend/pull/2072 the GitHub Workspace is correctly added to the allow list, however this action navigates to another directory which is not necessarily the workspace.
Add `$PWD` to Git's `safe.directory` allow list instead of `$GITHUB_WORKSPACE`.
=> fix(github-pages): Use PWD instead of workspace

.github/workflows/build-test-deploy.yml, .github/workflows/monorepo-deploy.yml, components/legacy-components/package-lock.json, components/legacy-components/package.json, components/legacy-components/src/article-card/article-card.scss, components/legacy-components/src/form/form.scss, components/legacy-components/src/form/index.js, components/legacy-components/src/form/inline-group.jsx, components/legacy-components/src/form/submit.jsx, components/legacy-components/src/header/header.js, components/legacy-components/src/header/header.scss, components/legacy-components/src/share-widget/share-widget.js, components/legacy-components/src/share-widget/share-widget.scss, components/legacy-components/src/util-grid/grid.scss, components/legacy-components/src/util-palette/palette.scss, components/legacy-components/src/util-typography/typography.scss, package-lock.json, services/cms/package-lock.json, services/cms/package.json, services/personal-website/src/components/layout.js, services/personal-website/src/components/related-articles.js, services/personal-website/src/pages/consultancy.js, services/personal-website/src/scss/pages/_article.scss, services/personal-website/src/scss/pages/_home.scss, services/personal-website/src/templates/article.js, services/personal-website/src/templates/talk.js, services/personal-website/static/svg/email.svg, services/personal-website/static/svg/rss.svg
For a while there have been a few small problems with the reading-experience, accessibility & conversion of article pages.
Add a new "Follow & share" footer to articles, widen the header & move everything else into a redesigned aside/RHR.
* Move Article page to use CSS Grid.
* Add back text decoration to all links.
* New InfoBox component.
* New InlineGroup form component.
* New SVGs for RSS & Email.
* Increase maximum viewport to 1020px.
* Change header to include "Writing" & "Speaking" + rewrite sub-header copy.
* Add new "Follow" block.
* Remove `gatsby-link` dependency from `legacy-components` package.
* Temporarily enable `legacy-peer-deps` behaviour for NPM.
* Clean up a few components.
The most substantial refactor of the article page in a few years: can't be sure it's completely …
=> feat: Article page reshuffle

components/legacy-components/src/header/header.js, components/legacy-components/src/header/header.scss, components/legacy-components/src/util-palette/palette.scss
Navigation currently doesn't fit well on smaller screens, and links collapse together making it hard to read.
Added new aria-state `expanded` to the navigation, hidden by default.  When active it applies a `flex-wrap` and a new background colour to improve visibility.  To control this aria-state I have added a button controlling navigation `aria-expanded` w/ basic CSS animation.
This also updates the active state for `Writing` to be active for all content.  Ideally this should be somehow contextually aware beyond the URL path.
=> Responsive Navigation

services/personal-website/gatsby-config.js
Links in the RSS feed are currently invalid, breaking the feed for several clients!
Logic designed to remove a double `/` in the URL also rewrites the scheme.  e.g. `https://alexwilson.tech/` becomes `https:/alexwilson.tech`.  This PR updates this link creation to use the (now-available) URL API.
The URL constructor [applies a relative link to an origin](https://nodejs.org/api/url.html#new-urlinput-base) which is perfect for this use-case.
As this updates the GUID - this will probably confuse some RSS clients, so I'll include a warning in weeknotes.
If you're reading this from there, SORRY!
=> fix(rss): Construct absolute links w/ URL API

services/personal-website/src/scss/pages/_article.scss
Frame units deal with available space, and so when I'm using code blocks these can expand across the side of the page.
Move from frame units to percentages for the article page.
=> Enforce maximum width in article grid with percentage units

components/legacy-components/src/util-grid/grid.scss, services/personal-website/src/scss/pages/_article.scss
In #2108 I updated FR to %, but missed the top-level setting.  Meaning there was no max-width for phones!
Correct the %, and unify grid width.  This fixes responsive behaviour for all articles.
=> fix(article): Apply 100% max-width

.github/workflows/build-test-deploy.yml, services/personal-website/gatsby-config.js
Today the feed isn't validated allowing bugs (like #2105) to affect a significant number of readers.
Using `github.com/w3c/feedvalidator`, start validating the RSS feed in continuous integration, and fix some of the top errors.
This includes some breaking changes to feeds such as truncating articles & stripping out invalid tags, however GUIDs will not change again.
This workflow may prove useful when extracting feed functionality, and I'd like to separate it as its own GitHub action.
=> Validate & fix Feed

components/legacy-components/src/article-card/article-card.js, services/personal-website/gatsby-config.js, services/personal-website/gatsby-node.js, services/personal-website/package-lock.json, services/personal-website/package.json, services/personal-website/src/components/related-articles.js, services/personal-website/src/pages/blog.js, services/personal-website/src/pages/index.js, services/personal-website/src/pages/talks.js, services/personal-website/src/schema/on-create-node.js, services/personal-website/src/templates/article.js, services/personal-website/src/templates/talk.js, services/personal-website/src/templates/topic.js
In trying to open up horizons beyond Gatsby:
* It's impossible to do anything meaningful with Topics as they only exist inside a closure.
* Content/Articles are a mix between frontmatter & hacked-together fields.
* Port to a specific schema, built on-top of MarkdownRemark.
* Introduce two new content-types: `Content` & `Topic`
* Seed Topic with tags.
* Remove as many customisations as possible.
* Simplify the data-model.
This is the biggest change I've made in quite some time, effectively rewriting large portions of the back-end.  I'm playing this one carefully.
=> WIP: Update graphQL schema

components/legacy-components/src/header/header.scss
Using margin-based positioning results in _something_ but also introduces some layout weirdness and is janky on mobile devices.
Use top-down animation, powered by `transform: translate()`.
=> feat(header): Use translate for header animation

services/personal-website/gatsby-config.js, services/personal-website/gatsby-node.js, services/personal-website/package-lock.json, services/personal-website/package.json, services/personal-website/src/templates/article.js
Currently all pages on the site have the default twitter summary card information which leads to lower engagement.
Add Twitter summary cards, generating an image with the name of the post - and me!
For compatability with Gatsby plugins, including the one enabling this funcitonality, this PR also adds back the slug field to MarkdownRemark nodes.  They use this to write files to a location available to posts.
=> feat(twitter): Enable twitter social cards

services/personal-website/src/templates/article.js
Currently twitter cards don't render for article pages, despite adding additional metadata.
Specify all required fields, including the ones I assumed could be read from OG!
=> Twitter: Specify all twitter card fields

services/personal-website/src/templates/article.js
Header social links on article pages are broken because they lean on the default reach router implementation, which doesn't support external URLs.
Pass the Gatsby link implementation through.
=> Article: Pass Link implementation to header

services/personal-website/src/templates/article.js
I'm on Mastodon now, and eventually want to federate w/ ActivityPub.
Add it to the article promobox!
=> chore: Add Mastodon to promobox

components/legacy-components/src/util-typography/typography.scss
With lengthier articles, long lists can be difficult to read.
Add 1em of spacing between list-items.
This is a rather nasty shortcut and won't always be in-step with the modular scale.  That being said I am comfortable taking on this debt as I would already like to simplify the typography module.
=> Add spacing between list-items

services/personal-website/src/scss/pages/_article.scss
Article layout makes use of CSS grid to separate the side-bar and the content-well.  In many cases it overflows due to the addition of percentages and em units.
(`grid-template-columns: 50% 50%` + `grid-column-gap: 1em` ~= `width: calc(100%+1em)`)
Replace usage of percentages in grid-template-columns definitions with fr, which take into account free space available after the gap (in em).
=> Fix article widths

services/personal-website/src/scss/pages/_article.scss
Since https://github.com/alexwilson/frontend/pull/2238, layout is now calculated and not imposed. Unfortunately that means that if you have an element that is particularly wide, you get this...
Apply `overflow: auto;` to the article content well so that wide elements are either clamped or cropped.
=> Force code blocks to be responsive

services/personal-website/src/templates/article.js
Revue is long gone!
Move newsletter to Mailchimp.
=> feat: Move emails to Mailchimp

package-lock.json, package.json
Lerna V7 removes legacy package management tools, migrating to workspaces.  This repo is not yet using workspaces (deliberately).  This change has halted builds.
Add `@lerna/legacy-package-management` which polyfills Lerna's old behaviour.  This fixes builds.
=> fix: Add @lerna/legacy-package-management

.github/workflows/monorepo-deploy.yml
Github are deprecated the `::set-output` directive which the CI workflow uses to discover repositories.  [More here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
Start migrating to `GITHUB_OUTPUT ` state.
=> CI: Migrate from `set-output` to GITHUB_OUTPUT

.github/workflows/monorepo-deploy.yml
Whoops, looks like I broke monorepo deploys that relied on dev tools (i.e. CMS) in https://github.com/alexwilson/frontend/pull/2283!
Allow production dependencies to be installed in `deploy`.
=> fix: Use dev deps when deploying

package-lock.json, services/auth-cms/package.json, services/auth-cms/wrangler.toml, services/cms/package.json, services/cms/webpack.client.cjs, services/cms/webpack.worker.cjs, services/cms/wrangler.toml, services/pictures/package.json, services/pictures/wrangler.toml, services/worker-cdn-prod/package.json, services/worker-cdn-prod/wrangler.toml
Wrangler V1 has been deprecated since last year and the hack that allowed it to work in CI no longer works since moving to NPM Workspaces.  Wrangler V2 brings a whole host of improvements.
Replace usage of Wrangler V1 with V2, setting the scene for V3.
Refactor CMS process very slightly to explicitly use custom Webpack for bundling the worker.
=> feat: Migrate to Wrangler V2

services/worker-cdn-prod/package.json
Something in the upgrade from Wrangler 1 to 2/3 has broken this particular worker.  I have raised an issue for it [here](https://github.com/alexwilson/frontend/issues/2313).
Disable deploys for worker-cdn-prod by replacing `wrangler publish` with `exit 0`.  This is a successful error code so it doesn't break other builds.
=> fix: Disable worker-cdn-prod deploys

components/legacy-components/src/util-typography/typography.scss, services/personal-website/gatsby-browser.js, services/personal-website/src/scss/main.scss
As reported in #2384, PrismJS fonts don't inherit correctly as they're overridden by the global `font-family` rule.
Temporarily patch this by forcing PrismJS spans to inherit their `font-family`.
=> Force PrismJS spans to inherit font

services/personal-website/gatsby-config.js
In some feed readers (looking at you, mailchimp) - not setting an author tag in the RSS feed results in the author appearing as "Anonymous". 
_(I've no idea who this anonymous chap is)_
Add author tag to feed items, defaulting to site title.
=> feat(rss): Add author tag

components/legacy-components/src/util-typography/type/_mixins.scss, components/legacy-components/src/util-typography/typography.scss, package-lock.json, services/cms/client/main.js, services/cms/client/preview/article.jsx, services/cms/package.json
Netlify CMS has been abandoned, and the project continues in Decap CMS.
1. Migrate Netlify CMS to Decap CMS.
2. Implement Article Preview styles.
This includes some changes to the version of Sassline used in the legacy typography module.  Instead of calculating and casting to EM, we now use a string-literal.
=> Migrate to Decap CMS

terraform/environments/prod.tfvars, terraform/environments/test.tfvars, terraform/main.tf, terraform/modules/cloudflare/main.tf, terraform/modules/cloudflare/outputs.tf, terraform/modules/cloudflare/variables.tf, terraform/variables.tf
Cloudflare is the next on my list of things to Terraform.
Move Page Rules for antoligy.com and ax.gy Cloudflare Zones into Terraform.
There's no way to run this in a test environment, so we set `count` to 0 in test and 1 in prod.
=> feat(terraform): Terraform the Cloudflare things

components/legacy-components/src/header/header.js, terraform/modules/fastly/vcl/main.vcl, terraform/modules/fastly/vcl/random-header-image.vcl, terraform/modules/fastly/vcl/redirects.vcl
Header images have been powered by Unsplash Source for quite some time, but they (quietly) deprecated it last year and recently decommissioned it.
1. Introduce a new endpoint (`/__service/random-header-image`) which returns a random image when called.
2. Change the reference to Unsplash to reference this instead.
This is extremely ugly, and I'm only doing this to buy time to reconsider the header more generally.
=> fix: temporarily swap unsplash for a fastly-hosted randomiser

terraform/environments/prod.tfvars, terraform/environments/test.tfvars, terraform/main.tf, terraform/modules/cloudflare/variables.tf, terraform/modules/fastly/honeycomb/format.json, terraform/modules/fastly/main.tf, terraform/modules/fastly/variables.tf, terraform/variables.tf
With the move to Fastly, I'm now able to configure logdrains!  I'm also finally able to gain some observability w/o client analytics.
Add Honeycomb logging to the Fastly module, and configure it for Test and Prod.
=> Add honeycomb logging

services/cms/client/config.yml, services/personal-website/gatsby-config.js, services/personal-website/gatsby-node.js, services/personal-website/src/components/related-articles.js, services/personal-website/src/pages/blog.js, services/personal-website/src/pages/talks.js, services/personal-website/src/schema/on-create-node.js, services/personal-website/src/templates/article.js
Currently - as I've written about in #1557 - we include legacy fields, and guess if a post is an article or a talk based on its collection.  
1. Remove legacy fields like `_legacy_slugs`  and `layout`.  The use-cases for `_legacy_slugs` were for redirects and webmentions, which have been resolved in Fastly (#2678) and Webmentions (#2692) respectively.
2. in Gatsby `onCreateNode` the `type` field now is based on the frontmatter property of the same name, instead of the collection we discovered the content in.
3. We now fetch the content collection once, for both collections.
After this is live, it is safe to merge `/talks/` and `/posts/` collections - however this should not be done until after this is merged.
=> Migrate discriminator logic to the type field, and remove other legacy fields

services/cms/client/config.yml, services/personal-website/gatsby-config.js
This is the final move in the game of 5D chess that has been #1557.  The `/talks/` collection is no longer used or useful, so let's remove it entirely.
Remove the `/talks/` collection from Personal-Website/Blog and CMS.
This relied on https://github.com/alexwilson/content/pull/188 merging the collections, which has gone perfectly.
=> Remove talks collection

pnpm-lock.yaml, services/cms/client/main.css, services/cms/client/main.js, services/cms/client/preview/article.jsx, services/cms/package.json, services/cms/webpack.client.cjs
Currently the CMS does not behave well on small screens, see #2731 for more details  .
* Add the responsive hack stylesheet from https://github.com/hithismani/responsive-decap in a new stylesheet.
* Add style-loader to inject styles from that stylesheet.
I'd much rather have referenced this package directly, but it doesn't include a package.json and so doesn't include any kind of export that can be resolved for `browser`.  I thought about contributing it, but it looks abandoned, so I'm adopting a copy *for now*.
=> feat: Hack CMS styles to include responsive overrides..

components/legacy-components/src/header/header.js, services/personal-website/src/pages/blog.js, services/personal-website/src/pages/talks.js, services/personal-website/src/templates/article.js, services/personal-website/src/templates/talk.js, services/personal-website/src/templates/topic.js
Since unifying talks and articles, there has been no differentiation between the two in the navigation. This PR restores that behaviour.
1. Add a new prop to the Header component called `section`.
2. It is an enum accepting two values atm: `blog` and `talks`.
3. Migrate all content pages to use one or the other.
* Lots of my PropTypes are incorrect, so it may be better to replace them all with typescript checks???? (jsdoc to avoid adding toolchain complexity before tearing out gatsby?!).
* The LinkImplementation prop probably should be a provider?  I'm not sure what the right pattern is here.
=> Add section prop to header to differentiate Blog and Talks sections.

.github/workflows/build-test-deploy.yml
GitHub have put Ubuntu 24.04 based runners into circulation, and these [do not have a supported/compatible](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json) version of Python 3.7, which is used for feed validation.
Pin the OS used for the Feed Validation task to Ubuntu 22.04, which is the version previously used, until I can do something more permanent (e.g. extracting this task).
=> Pin OS used for Feed Validation

services/personal-website/src/components/related-articles.js
When reading weeknotes on this blog, with the way that "read next" works, the previous weeknotes aren't reliably discoverable.  Only the most recent three (or four, if you visit the latest) are.
Change the related content logic to _always_ include the previous post tagged with `weeknotes`.
=> feat: Improve discoverability of previous weeknotes

components/legacy-components/package.json, pnpm-lock.yaml, services/cms/package.json, services/personal-website/package.json
New major release of React has broken builds.  I have not yet looked into why!
Reverts alexwilson/frontend#3077
=> Revert "chore(deps): bump react from 18.3.1 to 19.0.0"

.github/dependabot.yml, pnpm-lock.yaml, services/cms/package.json, services/cms/webpack.client.cjs
Recent Decap updates have introduced dependency issues, both with external dependencies (undeclared peer dependencies) and with internal dependencies (circular dependency resulting in module resolution failures).
These issues are present in all versions north of 3.5, so, for now let's ignore them.
Downgrade the Decap dependency to 3.4.0 which is the last stable version, and ignore updates to 3.5 and up.
Also fix a duplicate key in webpack (minor).
Let's undo this change once https://github.com/decaporg/decap-cms/pull/7394 and https://github.com/decaporg/decap-cms/pull/7405/files are fixed.
=> Downgrade Decap to 3.4.0

.github/workflows/terraform.yml
Custom VCL left unchecked can grow quite complicated quite quickly, and in this repository I carry a fair amount of custom VCL.
Use Falco to lint and test VCL files.
* We only listen to Falco VCL errors, and not warnings, as using the split boilerplate triggers a lot of warnings.
* This also bumps `actions/checkout` to v4 which introduces no major breaking changes.
=> Add Lint & Test CI steps for Fastly VCL

.github/dependabot.yml, pnpm-lock.yaml, services/cms/package.json, services/personal-website/package.json
In https://github.com/alexwilson/frontend/pull/3319 Dependabot pushed an update to ReactDOM 18.3.
This breaks bundling!  I thought that blocking React updates would prevent this from happening.  But they did not.
Cap ReactDOM to 18.
=> Downgrade ReactDOM to 18.3

.github/dependabot.yml, pnpm-lock.yaml, services/auth-cms/package.json, services/cms/package.json
Wrangler removed the `wrangler publish` command, which we accidentally included in https://github.com/alexwilson/frontend/pull/3297.
Downgrade wrangler back to 3.x.
=> fix: downgrade wrangler to 3.x

.github/workflows/build-test-deploy.yml, .github/workflows/monorepo-deploy.yml
For all new merges, this repository has two required status checks: Test & Tests Passed.
Some pull-requests are merged even when these status checks have not passed, leading to breakages and problems.
To see if this makes any difference, we now always run the required steps up to the required status-checks, and fail them *explicitly* if a prior step has not succeeded.
=> explicitly fail CI when important steps fail

.github/dependabot.yml, services/auth-cms/package.json, services/cms/package.json
New versions of Wrangler remove the `wrangler publish` command.
Change uses of `wrangler publish` to its replacement `wrangler deploy`.
=> fix: wrangler publish -> wrangler deploy
